<a href="https://colab.research.google.com/github/julia-azv/GitConcepts/blob/main/Course_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a=np.array([1,2,3], dtype='int32')
print (a)

[1 2 3]


In [ ]:
a.ndim #dimension
a.shape #taille

(3,)

In [ ]:
import numpy as np
b=np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [ ]:
b.ndim
b.shape
b.dtype

dtype('float64')

In [ ]:
np.random.randint(-4,8,size=(3,3))
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
arr=np.array([1,2,3])
r1=np.repeat(arr,3,axis=0)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [ ]:
output=np.ones((5,5))
print(output)

z=np.zeros((3,3))
z[1,1]=9
print(z)

output[1:-1,1:-1]=z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
a=np.ones((2,3))
print(a)

b=np.full((3,2),2)
print(b)

np.matmul(a,b)

d=np.random.rand(2,3)
print(d)

e=np.random.randint(-5,5,size=(3,2))
print(e)

print(np.matmul(d,e))  #matrice multiplication
print(np.matmul(e,d))

f=np.random.randint(-10,10,size=(4,4))
print(f)

g=np.random.randint(-4,10,size=(3,3))
print(g)

print(np.linalg.det(f))
print(np.linalg.det(g))

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]
[[0.09016314 0.23660002 0.02770037]
 [0.78247489 0.19432782 0.08316378]]
[[-3 -4]
 [-4 -4]
 [ 2  1]]
[[-1.16148874 -1.27935225]
 [-2.95840838 -3.82404706]]
[[-3.40038897 -1.48711133 -0.41575624]
 [-3.49055211 -1.72371135 -0.44345661]
 [ 0.96280117  0.66752785  0.13856452]]
[[-4 -1  3 -4]
 [ 3 -4  9  9]
 [-8 -9  3  1]
 [-1 -9  9  4]]
[[7 9 6]
 [4 8 0]
 [3 5 8]]
2289.0000000000005
136.00000000000006


In [ ]:
stats=np.array([[1,2,3],[4,5,6]])
stats
np.min(stats)
np.max(stats)
np.max(stats,axis=0)
np.min(stats,axis=0)
np.min(stats,axis=1)
np.sum(stats,axis=1)

array([ 6, 15])

In [ ]:
arr=np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=-2)
print(r1)


[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
import numpy as np
smooth1=[1,2.5,3,4.5,5]
arr1=np.array(smooth1)
print(arr1)
smooth2=[1.5,1j+2,2.5,3,3.5]
arr2=np.array(smooth2)
print(arr2)

[1.  2.5 3.  4.5 5. ]
[1.5+0.j 2. +1.j 2.5+0.j 3. +0.j 3.5+0.j]


In [ ]:
import numpy as np
a=np.random.randint(10,30,size=(1,30))
a[0,4]=1
print(a)

[[22 17 22 16  1 10 10 27 21 26 27 26 26 26 13 10 10 20 20 17 16 21 27 16
  24 17 19 14 19 17]]
